export const stays = [
  //amazing-views
  {
    id: 1,
    title: "Bhitar Wali, India",
    image: [
      "/project_airBNB/Amazing views/Bhitar Wali, India/img1.avif",
      "/project_airBNB/Amazing views/Bhitar Wali, India/img2.avif",
      "/project_airBNB/Amazing views/Bhitar Wali, India/img3.avif",
      "/project_airBNB/Amazing views/Bhitar Wali, India/img4.avif",
      "/project_airBNB/Amazing views/Bhitar Wali, India/img5.avif",
    ],
    locationType: "amazing-views",
    price: "₹121,044 for 5 nights",
  },
  {
    id: 2,
    title: "Cheog, India",
    image: [
      "/project_airBNB/Amazing views/Cheog, India/img2.avif",
      "/project_airBNB/Amazing views/Cheog, India/img3.avif",
      "/project_airBNB/Amazing views/Cheog, India/img4.avif",
      "/project_airBNB/Amazing views/Cheog, India/img5.avif",
      "/project_airBNB/Amazing views/Cheog, India/img1.avif",
    ],
    locationType: "amazing-views",
    price: "₹184,125 for 5 nights",
  },
  {
    id: 3,
    title: "Gurugram, India",
    image: [
      "/project_airBNB/Amazing views/Gurugram, India/img2.avif",
      "/project_airBNB/Amazing views/Gurugram, India/img3.avif",
      "/project_airBNB/Amazing views/Gurugram, India/img4.avif",
      "/project_airBNB/Amazing views/Gurugram, India/img5.avif",
      "/project_airBNB/Amazing views/Gurugram, India/img1.avif",
    ],
    locationType: "amazing-views",
    price: "₹123,242 for 5 nights",
  },
  {
    id: 4,
    title: "jibhi, India",
    image: [
      "/project_airBNB/Amazing views/Jibhi, India/img2.avif",
      "/project_airBNB/Amazing views/Jibhi, India/img3.avif",
      "/project_airBNB/Amazing views/Jibhi, India/img4.avif",
      "/project_airBNB/Amazing views/Jibhi, India/img5.avif",
      "/project_airBNB/Amazing views/Jibhi, India/img1.avif",
    ],
    locationType: "amazing-views",
    price: "₹141,448 for 5 nights",
  },
  {
    id: 5,
    title: "Kotgarh, India",
    image: [
      "/project_airBNB/Amazing views/Kotgarh, India/img1.avif",
      "/project_airBNB/Amazing views/Kotgarh, India/img2.avif",
      "/project_airBNB/Amazing views/Kotgarh, India/img3.jpeg",
      "/project_airBNB/Amazing views/Kotgarh, India/img4.avif",
      "/project_airBNB/Amazing views/Kotgarh, India/img5.avif",
    ],
    locationType: "amazing-views",
    price: "₹220,486 for 5 nights",
  },
  {
    id: 6,
    title: "Manali, India",
    image: [
      "/project_airBNB/Amazing views/Manali, India/img2.avif",
      "/project_airBNB/Amazing views/Manali, India/img3.avif",
      "/project_airBNB/Amazing views/Manali, India/img4.avif",
      "/project_airBNB/Amazing views/Manali, India/img5.avif",
      "/project_airBNB/Amazing views/Manali, India/img1.avif",
    ],
    locationType: "amazing-views",
    price: "₹237,659 for 5 nights",
  },
  {
    id: 7,
    title: "Mussoorie, India",
    image: [
      "/project_airBNB/Amazing views/Mussoorie, India/img2.avif",
      "/project_airBNB/Amazing views/Mussoorie, India/img3.avif",
      "/project_airBNB/Amazing views/Mussoorie, India/img4.avif",
      "/project_airBNB/Amazing views/Mussoorie, India/img5.avif",
      "/project_airBNB/Amazing views/Mussoorie, India/img1.avif",
    ],
    locationType: "amazing-views",
    price: "₹224,478 for 5 nights",
  },
  {
    id: 8,
    title: "Sajla, India",
    image: [
      "/project_airBNB/Amazing views/Sajla, India/img2.avif",
      "/project_airBNB/Amazing views/Sajla, India/img3.avif",
      "/project_airBNB/Amazing views/Sajla, India/img4.avif",
      "/project_airBNB/Amazing views/Sajla, India/img5.avif",
      "/project_airBNB/Amazing views/Sajla, India/img1.avif",
    ],
    locationType: "amazing-views",
    price: "₹223,173 for 5 nights",
  },
  {
    id: 9,
    title: "Suwakholi, India",
    image: [
      "/project_airBNB/Amazing views/Suwakholi, India/img1.avif",
      "/project_airBNB/Amazing views/Suwakholi, India/img2.avif",
      "/project_airBNB/Amazing views/Suwakholi, India/img3.avif",
      "/project_airBNB/Amazing views/Suwakholi, India/img4.avif",
      "/project_airBNB/Amazing views/Suwakholi, India/img5.avif",
    ],
    locationType: "amazing-views",
    price: "₹453,139 for 5 nights",
  },
  {
    id: 10,
    title: "Theog, India",
    image: [
      "/project_airBNB/Amazing views/Theog, India/img1.avif",
      "/project_airBNB/Amazing views/Theog, India/img2.avif",
      "/project_airBNB/Amazing views/Theog, India/img3.avif",
      "/project_airBNB/Amazing views/Theog, India/img4.avif",
      "/project_airBNB/Amazing views/Theog, India/img5.avif",
    ],

    locationType: "amazing-views",
    price: "₹223,511 for 5 nights",
  },

  //beachfronts
  {
    id: 11,
    title: "Canacona, India",
    image: [
      "/project_airBNB/Beachfronts/Canacona, India/img1.avif",
      "/project_airBNB/Beachfronts/Canacona, India/img2.avif",
      "/project_airBNB/Beachfronts/Canacona, India/img3.avif",
      "/project_airBNB/Beachfronts/Canacona, India/img4.avif",
      "/project_airBNB/Beachfronts/Canacona, India/img5.avif",
    ],
    locationType: "beachfront",
    price: "₹207,568 for 5 nights",
  },
  {
    id: 12,
    title: "Candolim, India",
    image: [
      "/project_airBNB/Beachfronts/Candolim, India/img1.avif",
      "/project_airBNB/Beachfronts/Candolim, India/img2.avif",
      "/project_airBNB/Beachfronts/Candolim, India/img3.avif",
      "/project_airBNB/Beachfronts/Candolim, India/img4.avif",
      "/project_airBNB/Beachfronts/Candolim, India/img5.avif",
    ],
    locationType: "beachfront",
    price: "₹246,227 for 5 nights",
  },
  {
    id: 13,
    title: "Haleyangadi, India",
    image: [
      "/project_airBNB/Beachfronts/Haleyangadi, India/img1.avif",
      "/project_airBNB/Beachfronts/Haleyangadi, India/img2.avif",
      "/project_airBNB/Beachfronts/Haleyangadi, India/img3.avif",
      "/project_airBNB/Beachfronts/Haleyangadi, India/img4.avif",
      "/project_airBNB/Beachfronts/Haleyangadi, India/img5.avif",
    ],
    locationType: "beachfront",
    price: "₹172,095 for 5 nights",
  },
  {
    id: 14,
    title: "Hua Hin, Thailand",
    image: [
      "/project_airBNB/Beachfronts/Hua Hin, Thailand/img1.avif",
      "/project_airBNB/Beachfronts/Hua Hin, Thailand/img2.avif",
      "/project_airBNB/Beachfronts/Hua Hin, Thailand/img3.avif",
      "/project_airBNB/Beachfronts/Hua Hin, Thailand/img4.avif",
      "/project_airBNB/Beachfronts/Hua Hin, Thailand/img5.avif",
    ],
    locationType: "beachfront",
    price: "₹259,415 for 5 nights",
  },
  {
    id: 15,
    title: "Ko Tao, Thailand",
    image: [
      "/project_airBNB/Beachfronts/Ko Tao, Thailand/img1.avif",
      "/project_airBNB/Beachfronts/Ko Tao, Thailand/img2.webp",
      "/project_airBNB/Beachfronts/Ko Tao, Thailand/img3.webp",
      "/project_airBNB/Beachfronts/Ko Tao, Thailand/img4.webp",
      "/project_airBNB/Beachfronts/Ko Tao, Thailand/img5.avif",
      "/project_airBNB/Beachfronts/Ko Tao, Thailand/img6.webp",
    ],
    locationType: "beachfront",
    price: "₹326,979 for 5 nights",
  },
  {
    id: 16,
    title: "Mae Nam, Thailand",
    image: [
      "/project_airBNB/Beachfronts/Mae Nam, Thailand/img1.avif",
      "/project_airBNB/Beachfronts/Mae Nam, Thailand/img2.avif",
      "/project_airBNB/Beachfronts/Mae Nam, Thailand/img3.avif",
      "/project_airBNB/Beachfronts/Mae Nam, Thailand/img4.avif",
      "/project_airBNB/Beachfronts/Mae Nam, Thailand/img5.jpeg",
    ],
    locationType: "beachfront",
    price: "₹534,011 for 5 nights",
  },
  {
    id: 17,
    title: "Mangaluru, India",
    image: [
      "/project_airBNB/Beachfronts/Mangaluru, India/img1.avif",
      "/project_airBNB/Beachfronts/Mangaluru, India/img2.avif",
      "/project_airBNB/Beachfronts/Mangaluru, India/img3.avif",
      "/project_airBNB/Beachfronts/Mangaluru, India/img4.avif",
      "/project_airBNB/Beachfronts/Mangaluru, India/img5.avif",
    ],
    locationType: "beachfront",
    price: "₹382,432 for 5 nights",
  },
  {
    id: 18,
    title: "Phang Nga, Thailand",
    image: [
      "/project_airBNB/Beachfronts/Phang Nga, Thailand/img1.avif",
      "/project_airBNB/Beachfronts/Phang Nga, Thailand/img2.avif",
      "/project_airBNB/Beachfronts/Phang Nga, Thailand/img3.avif",
      "/project_airBNB/Beachfronts/Phang Nga, Thailand/img4.avif",
      "/project_airBNB/Beachfronts/Phang Nga, Thailand/img5.avif",
    ],
    locationType: "beachfront",
    price: "₹220,222 for 5 nights",
  },
  {
    id: 19,
    title: "Ko Samui, Thailand",
    image: [
      "/project_airBNB/Beachfronts/Ko Samui, Thailand/img1.avif",
      "/project_airBNB/Beachfronts/Ko Samui, Thailand/img2.avif",
      "/project_airBNB/Beachfronts/Ko Samui, Thailand/img3.avif",
      "/project_airBNB/Beachfronts/Ko Samui, Thailand/img4.avif",
      "/project_airBNB/Beachfronts/Ko Samui, Thailand/img5.avif",
    ],
    locationType: "beachfront",
    price: "₹355,398 for 5 nights",
  },
  {
    id: 20,
    title: "Tambon Bo Put, Thailand",
    image: [
      "/project_airBNB/Beachfronts/Tambon Bo Put, Thailand/img1.avif",
      "/project_airBNB/Beachfronts/Tambon Bo Put, Thailand/img2.jpeg",
      "/project_airBNB/Beachfronts/Tambon Bo Put, Thailand/img3.avif",
      "/project_airBNB/Beachfronts/Tambon Bo Put, Thailand/img4.avif",
      "/project_airBNB/Beachfronts/Tambon Bo Put, Thailand/img5.avif",
    ],
    locationType: "beachfront",
    price: "₹362,198 for 5 nights",
  },

  //castles
  {
    id: 21,
    title: "boutique hotel in Sinaia, Romania",
    image: [
      "/project_airBNB/Castles/boutique hotel in Sinaia, Romania/img1.avif",
      "/project_airBNB/Castles/boutique hotel in Sinaia, Romania/img2.avif",
      "/project_airBNB/Castles/boutique hotel in Sinaia, Romania/img3.avif",
      "/project_airBNB/Castles/boutique hotel in Sinaia, Romania/img4.avif",
      "/project_airBNB/Castles/boutique hotel in Sinaia, Romania/img5.jpg",
    ],
    locationType: "castles",
    price: "₹156,899 for 5 nights",
  },
  {
    id: 22,
    title: "Bujra, India",
    image: [
      "/project_airBNB/Castles/Bujra, India/img1.avif",
      "/project_airBNB/Castles/Bujra, India/img2.avif",
      "/project_airBNB/Castles/Bujra, India/img3.avif",
      "/project_airBNB/Castles/Bujra, India/img4.avif",
      "/project_airBNB/Castles/Bujra, India/img5.avif",
    ],
    locationType: "castles",
    price: "₹1,264,021 for 5 nights",
  },
  {
    id: 23,
    title: "Carovigno, Italy",
    image: [
      "/project_airBNB/Castles/Carovigno, Italy/img1.avif",
      "/project_airBNB/Castles/Carovigno, Italy/img2.avif",
      "/project_airBNB/Castles/Carovigno, Italy/img3.avif",
      "/project_airBNB/Castles/Carovigno, Italy/img4.avif",
      "/project_airBNB/Castles/Carovigno, Italy/img5.avif",
    ],
    locationType: "castles",
    price: "₹1,065,346 for 5 nights",
  },
  {
    id: 24,
    title: "Klipphausen, Germany",
    image: [
      "/project_airBNB/Castles/Klipphausen, Germany/img1.avif",
      "/project_airBNB/Castles/Klipphausen, Germany/img2.avif",
      "/project_airBNB/Castles/Klipphausen, Germany/img3.avif",
      "/project_airBNB/Castles/Klipphausen, Germany/img4.avif",
      "/project_airBNB/Castles/Klipphausen, Germany/img5.avif",
    ],
    locationType: "castles",
    price: "₹132,550 for 5 nights",
  },
  {
    id: 25,
    title: "Ljusdal, Sweden",
    image: [
      "/project_airBNB/Castles/Ljusdal, Sweden/img1.avif",
      "/project_airBNB/Castles/Ljusdal, Sweden/img2.avif",
      "/project_airBNB/Castles/Ljusdal, Sweden/img3.jpg",
      "/project_airBNB/Castles/Ljusdal, Sweden/img4.avif",
      "/project_airBNB/Castles/Ljusdal, Sweden/img5.avif",
    ],
    locationType: "castles",
    price: "₹269,843 for 5 nights",
  },
  {
    id: 26,
    title: "Mikri Mantineia, Greece",
    image: [
      "/project_airBNB/Castles/Mikri Mantineia, Greece/img1.avif",
      "/project_airBNB/Castles/Mikri Mantineia, Greece/img2.avif",
      "/project_airBNB/Castles/Mikri Mantineia, Greece/img3.avif",
      "/project_airBNB/Castles/Mikri Mantineia, Greece/img4.avif",
      "/project_airBNB/Castles/Mikri Mantineia, Greece/img5.avif",
    ],
    locationType: "castles",
    price: "₹67,206 for 5 nights",
  },
  {
    id: 27,
    title: "Osowa Sień, Poland",
    image: [
      "/project_airBNB/Castles/Osowa Sień, Poland/img1.avif",
      "/project_airBNB/Castles/Osowa Sień, Poland/img2.avif",
      "/project_airBNB/Castles/Osowa Sień, Poland/img3.avif",
      "/project_airBNB/Castles/Osowa Sień, Poland/img4.avif",
      "/project_airBNB/Castles/Osowa Sień, Poland/img5.avif",
    ],
    locationType: "castles",
    price: "₹64,785 for 5 nights",
  },
  {
    id: 28,
    title: "Positano, Italy",
    image: [
      "/project_airBNB/Castles/Positano, Italy/img1.avif",
      "/project_airBNB/Castles/Positano, Italy/img2.avif",
      "/project_airBNB/Castles/Positano, Italy/img3.avif",
      "/project_airBNB/Castles/Positano, Italy/img4.avif",
      "/project_airBNB/Castles/Positano, Italy/img5.avif",
    ],
    locationType: "castles",
    price: "₹320,700 for 5 nights",
  },
  {
    id: 29,
    title: "Preding, Austria",
    image: [
      "/project_airBNB/Castles/Preding, Austria/img1.avif",
      "/project_airBNB/Castles/Preding, Austria/img2.avif",
      "/project_airBNB/Castles/Preding, Austria/img3.avif",
      "/project_airBNB/Castles/Preding, Austria/img4.avif",
      "/project_airBNB/Castles/Preding, Austria/img5.avif",
    ],
    locationType: "castles",
    price: "₹361,852 for 5 nights",
  },
  {
    id: 30,
    title: "Vilémov, Czechia",
    image: [
      "/project_airBNB/Castles/Vilémov, Czechia/img1.avif",
      "/project_airBNB/Castles/Vilémov, Czechia/img2.avif",
      "/project_airBNB/Castles/Vilémov, Czechia/img3.avif",
      "/project_airBNB/Castles/Vilémov, Czechia/img4.avif",
      "/project_airBNB/Castles/Vilémov, Czechia/img5.jpeg",
    ],
    locationType: "castles",
    price: "₹706,602 for 5 nights",
  },

  //lake
  {
    id: 31,
    title: "Canacona, India",
    image: [
      "/project_airBNB/Lake/Canacona, India/img1.webp",
      "/project_airBNB/Lake/Canacona, India/img2.avif",
      "/project_airBNB/Lake/Canacona, India/img3.avif",
      "/project_airBNB/Lake/Canacona, India/img4.avif",
      "/project_airBNB/Lake/Canacona, India/img5.avif",
    ],
    locationType: "lake",
    price: "₹172,974 for 5 nights",
  },
  {
    id: 32,
    title: "Chopdem, India",
    image: [
      "/project_airBNB/Lake/Chopdem, India/img1.avif",
      "/project_airBNB/Lake/Chopdem, India/img2.avif",
      "/project_airBNB/Lake/Chopdem, India/img3.avif",
      "/project_airBNB/Lake/Chopdem, India/img4.avif",
      "/project_airBNB/Lake/Chopdem, India/img5.avif",
      "/project_airBNB/Lake/Chopdem, India/img6.jpeg",
    ],
    locationType: "lake",
    price: "₹379,900 for 5 nights",
  },
  {
    id: 33,
    title: "Mandrem, India",
    image: [
      "/project_airBNB/Lake/Mandrem, India/img1.avif",
      "/project_airBNB/Lake/Mandrem, India/img2.avif",
      "/project_airBNB/Lake/Mandrem, India/img3.avif",
      "/project_airBNB/Lake/Mandrem, India/img4.avif",
      "/project_airBNB/Lake/Mandrem, India/img5.avif",
      "/project_airBNB/Lake/Mandrem, India/img6.avif",
    ],
    locationType: "lake",
    price: "₹343,154 for 5 nights",
  },
  {
    id: 34,
    title: "Mussoorie, India",
    image: [
      "/project_airBNB/Lake/Mussoorie, India/img1.avif",
      "/project_airBNB/Lake/Mussoorie, India/img2.avif",
      "/project_airBNB/Lake/Mussoorie, India/img3.avif",
      "/project_airBNB/Lake/Mussoorie, India/img4.avif",
      "/project_airBNB/Lake/Mussoorie, India/img5.avif",
    ],
    locationType: "lake",
    price: "₹354,206 for 5 nights",
  },
  {
    id: 35,
    title: "Nerul, India",
    image: [
      "/project_airBNB/Lake/Nerul, India/img1.avif",
      "/project_airBNB/Lake/Nerul, India/img2.avif",
      "/project_airBNB/Lake/Nerul, India/img3.avif",
      "/project_airBNB/Lake/Nerul, India/img4.avif",
      "/project_airBNB/Lake/Nerul, India/img5.avif",
    ],
    locationType: "lake",
    price: "₹358,900 for 5 nights",
  },
  {
    id: 36,
    title: "Rishikesh, India",
    image: [
      "/project_airBNB/Lake/Rishikesh, India/img1.avif",
      "/project_airBNB/Lake/Rishikesh, India/img2.avif",
      "/project_airBNB/Lake/Rishikesh, India/img3.avif",
      "/project_airBNB/Lake/Rishikesh, India/img4.avif",
      "/project_airBNB/Lake/Rishikesh, India/img5.avif",
    ],
    locationType: "lake",
    price: "₹332,509 for 5 nights",
  },
  {
    id: 37,
    title: "Sagara, India",
    image: [
      "/project_airBNB/Lake/Sagara, India/img1.avif",
      "/project_airBNB/Lake/Sagara, India/img2.jpeg",
      "/project_airBNB/Lake/Sagara, India/img3.avif",
      "/project_airBNB/Lake/Sagara, India/img4.avif",
      "/project_airBNB/Lake/Sagara, India/img5.jpeg",
    ],
    locationType: "lake",
    price: "₹170,100 for 5 nights",
  },
  {
    id: 38,
    title: "Sanguri Gaon, India",
    image: [
      "/project_airBNB/Lake/Sanguri Gaon, India/img1.avif",
      "/project_airBNB/Lake/Sanguri Gaon, India/img2.avif",
      "/project_airBNB/Lake/Sanguri Gaon, India/img3.jpeg",
      "/project_airBNB/Lake/Sanguri Gaon, India/img4.avif",
      "/project_airBNB/Lake/Sanguri Gaon, India/img5.avif",
    ],
    locationType: "lake",
    price: "₹328,680 for 7 nights",
  },
  {
    id: 39,
    title: "Shangarh, India",
    image: [
      "/project_airBNB/Lake/Shangarh, India/img1.avif",
      "/project_airBNB/Lake/Shangarh, India/img2.jpeg",
      "/project_airBNB/Lake/Shangarh, India/img3.avif",
      "/project_airBNB/Lake/Shangarh, India/img4.avif",
      "/project_airBNB/Lake/Shangarh, India/img5.avif",
    ],
    locationType: "lake",
    price: "₹242,586 for 5 nights",
  },
  {
    id: 40,
    title: "Siolim, India",
    image: [
      "/project_airBNB/Lake/Siolim, India/img1.avif",
      "/project_airBNB/Lake/Siolim, India/img2.avif",
      "/project_airBNB/Lake/Siolim, India/img3.avif",
      "/project_airBNB/Lake/Siolim, India/img4.avif",
      "/project_airBNB/Lake/Siolim, India/img5.webp",
    ],
    locationType: "lake",
    price: "₹171,118 for 5 nights",
  },

  //mensions
  {
    id: 41,
    title: "Baga, India",
    image: [
      "/project_airBNB/Mansions/Baga, India/img (1).avif",
      "/project_airBNB/Mansions/Baga, India/img (2).avif",
      "/project_airBNB/Mansions/Baga, India/img (3).avif",
      "/project_airBNB/Mansions/Baga, India/img (4).avif",
      "/project_airBNB/Mansions/Baga, India/img (5).avif",
    ],
    locationType: "mansions",
    price: "₹189,000 for 5 nights",
  },
  {
    id: 42,
    title: "Bhimtal, India",
    image: [
      "/project_airBNB/Mansions/Bhimtal, India/img (1).avif",
      "/project_airBNB/Mansions/Bhimtal, India/img (2).avif",
      "/project_airBNB/Mansions/Bhimtal, India/img (3).avif",
      "/project_airBNB/Mansions/Bhimtal, India/img (4).avif",
      "/project_airBNB/Mansions/Bhimtal, India/img (5).jpg",
    ],
    locationType: "mansions",
    price: "₹1,380,450 for 5 nights",
  },
  {
    id: 43,
    title: "Calangute, India",
    image: [
      "/project_airBNB/Mansions/Calangute, India/img (1).avif",
      "/project_airBNB/Mansions/Calangute, India/img (2).avif",
      "/project_airBNB/Mansions/Calangute, India/img (3).avif",
      "/project_airBNB/Mansions/Calangute, India/img (4).avif",
      "/project_airBNB/Mansions/Calangute, India/img (5).avif",
    ],
    locationType: "mansions",
    price: "₹1,230,300 for 5 nights",
  },
  {
    id: 44,
    title: "Choeng Thale, Thailand",
    image: [
      "/project_airBNB/Mansions/Choeng Thale, Thailand/img (1).avif",
      "/project_airBNB/Mansions/Choeng Thale, Thailand/img (2).avif",
      "/project_airBNB/Mansions/Choeng Thale, Thailand/img (3).avif",
      "/project_airBNB/Mansions/Choeng Thale, Thailand/img (4).avif",
      "/project_airBNB/Mansions/Choeng Thale, Thailand/img (5).avif",
    ],
    locationType: "mansions",
    price: "₹230,200 for 5 nights",
  },
  {
    id: 45,
    title: "Chopdem, India",
    image: [
      "/project_airBNB/Mansions/Chopdem, India/img (1).avif",
      "/project_airBNB/Mansions/Chopdem, India/img (2).avif",
      "/project_airBNB/Mansions/Chopdem, India/img (3).avif",
      "/project_airBNB/Mansions/Chopdem, India/img (4).avif",
      "/project_airBNB/Mansions/Chopdem, India/img (5).avif",
    ],
    locationType: "mansions",
    price: "₹201,957 for 5 nights",
  },
  {
    id: 46,
    title: "Karjat, India",
    image: [
      "/project_airBNB/Mansions/Karjat, India/img (1).avif",
      "/project_airBNB/Mansions/Karjat, India/img (2).avif",
      "/project_airBNB/Mansions/Karjat, India/img (3).avif",
      "/project_airBNB/Mansions/Karjat, India/img (4).avif",
      "/project_airBNB/Mansions/Karjat, India/img (5).avif",
    ],
    locationType: "mansions",
    price: "₹5,00,600 for 5 nights",
  },
  {
    id: 47,
    title: "Lonavala, India",
    image: [
      "/project_airBNB/Mansions/Lonavala, India/img (1).avif",
      "/project_airBNB/Mansions/Lonavala, India/img (2).avif",
      "/project_airBNB/Mansions/Lonavala, India/img (3).avif",
      "/project_airBNB/Mansions/Lonavala, India/img (4).avif",
      "/project_airBNB/Mansions/Lonavala, India/img (5).avif",
    ],
    locationType: "mansions",
    price: "₹1,129,046 for 5 nights",
  },
  {
    id: 48,
    title: "Pa Klok, Thailand",
    image: [
      "/project_airBNB/Mansions/Pa Klok, Thailand/img (1).avif",
      "/project_airBNB/Mansions/Pa Klok, Thailand/img (5).jpg",
      "/project_airBNB/Mansions/Pa Klok, Thailand/img (3).avif",
      "/project_airBNB/Mansions/Pa Klok, Thailand/img (4).avif",
      "/project_airBNB/Mansions/Pa Klok, Thailand/img (2).avif",
    ],
    locationType: "mansions",
    price: "₹230,399 for 5 nights",
  },
  {
    id: 49,
    title: "Tambon Su Thep, Thailand",
    image: [
      "/project_airBNB/Mansions/Tambon Su Thep, Thailand/img (1).avif",
      "/project_airBNB/Mansions/Tambon Su Thep, Thailand/img (2).avif",
      "/project_airBNB/Mansions/Tambon Su Thep, Thailand/img (3).avif",
      "/project_airBNB/Mansions/Tambon Su Thep, Thailand/img (4).avif",
      "/project_airBNB/Mansions/Tambon Su Thep, Thailand/img (5).avif",
    ],
    locationType: "mansions",
    price: "₹1,122,032 for 5 nights",
  },
  {
    id: 50,
    title: "Udaipur, India",
    image: [
      "/project_airBNB/Mansions/Udaipur, India/img (1).avif",
      "/project_airBNB/Mansions/Udaipur, India/img (2).avif",
      "/project_airBNB/Mansions/Udaipur, India/img (3).avif",
      "/project_airBNB/Mansions/Udaipur, India/img (4).avif",
      "/project_airBNB/Mansions/Udaipur, India/img (5).avif",
    ],
    locationType: "mansions",
    price: "₹,200,400 for 5 nights",
  },

  //new
  {
    id: 51,
    title: "Avon, Colorado, United States",
    image: [
      "/project_airBNB/New/Avon, Colorado, United States/img (1).avif",
      "/project_airBNB/New/Avon, Colorado, United States/img (2).avif",
      "/project_airBNB/New/Avon, Colorado, United States/img (3).avif",
      "/project_airBNB/New/Avon, Colorado, United States/img (4).avif",
      "/project_airBNB/New/Avon, Colorado, United States/img (5).jpg",
    ],
    locationType: "new",
    price: "₹1,030,089 for 5 nights",
  },
  {
    id: 52,
    title: "Barreirinhas, Brazil",
    image: [
      "/project_airBNB/New/Barreirinhas, Brazil/img (1).avif",
      "/project_airBNB/New/Barreirinhas, Brazil/img (2).avif",
      "/project_airBNB/New/Barreirinhas, Brazil/img (3).avif",
      "/project_airBNB/New/Barreirinhas, Brazil/img (4).avif",
      "/project_airBNB/New/Barreirinhas, Brazil/img (5).jpg",
    ],
    locationType: "new",
    price: "₹948,832 for 5 nights",
  },
  {
    id: 53,
    title: "Bellaria-Igea Marina, Italy",
    image: [
      "/project_airBNB/New/Bellaria-Igea Marina, Italy/img (1).avif",
      "/project_airBNB/New/Bellaria-Igea Marina, Italy/img (2).avif",
      "/project_airBNB/New/Bellaria-Igea Marina, Italy/img (3).avif",
      "/project_airBNB/New/Bellaria-Igea Marina, Italy/img (4).avif",
      "/project_airBNB/New/Bellaria-Igea Marina, Italy/img (5).avif",
    ],
    locationType: "new",
    price: "₹716,647 for 5 nights",
  },
  {
    id: 54,
    title: "Broken Bow, Oklahoma, United States",
    image: [
      "/project_airBNB/New/Broken Bow, Oklahoma, United States/img (1).avif",
      "/project_airBNB/New/Broken Bow, Oklahoma, United States/img (2).avif",
      "/project_airBNB/New/Broken Bow, Oklahoma, United States/img (3).avif",
      "/project_airBNB/New/Broken Bow, Oklahoma, United States/img (4).avif",
      "/project_airBNB/New/Broken Bow, Oklahoma, United States/img (5).avif",
    ],
    locationType: "new",
    price: "₹919,032 for 5 nights",
  },
  {
    id: 55,
    title: "Butkovići, Croatia",
    image: [
      "/project_airBNB/New/Butkovići, Croatia/img (1).avif",
      "/project_airBNB/New/Butkovići, Croatia/img (2).avif",
      "/project_airBNB/New/Butkovići, Croatia/img (3).avif",
      "/project_airBNB/New/Butkovići, Croatia/img (4).avif",
      "/project_airBNB/New/Butkovići, Croatia/img (5).jpg",
    ],
    locationType: "new",
    price: "₹951,157 for 5 nights",
  },
  {
    id: 56,
    title: "Cha-am, Thailand",
    image: [
      "/project_airBNB/New/Cha-am, Thailand/img (1).avif",
      "/project_airBNB/New/Cha-am, Thailand/img (2).avif",
      "/project_airBNB/New/Cha-am, Thailand/img (3).avif",
      "/project_airBNB/New/Cha-am, Thailand/img (4).avif",
      "/project_airBNB/New/Cha-am, Thailand/img (5).avif",
    ],
    locationType: "new",
    price: "₹732,197 for 5 nights",
  },
  {
    id: 57,
    title: "Lac-Supérieur, Canada",
    image: [
      "/project_airBNB/New/Lac-Supérieur, Canada/img (1).avif",
      "/project_airBNB/New/Lac-Supérieur, Canada/img (2).avif",
      "/project_airBNB/New/Lac-Supérieur, Canada/img (3).avif",
      "/project_airBNB/New/Lac-Supérieur, Canada/img (4).avif",
      "/project_airBNB/New/Lac-Supérieur, Canada/img (5).avif",
    ],
    locationType: "new",
    price: "₹4,287,549 for 5 nights",
  },
  {
    id: 58,
    title: "Marrakesh, Morocco",
    image: [
      "/project_airBNB/New/Marrakesh, Morocco/img (1).avif",
      "/project_airBNB/New/Marrakesh, Morocco/img (2).avif",
      "/project_airBNB/New/Marrakesh, Morocco/img (3).avif",
      "/project_airBNB/New/Marrakesh, Morocco/img (4).avif",
      "/project_airBNB/New/Marrakesh, Morocco/img (5).avif",
    ],
    locationType: "new",
    price: "₹253,505 for 5 nights",
  },
  {
    id: 59,
    title: "Queenstown, New Zealand",
    image: [
      "/project_airBNB/New/Queenstown, New Zealand/img (1).avif",
      "/project_airBNB/New/Queenstown, New Zealand/img (2).avif",
      "/project_airBNB/New/Queenstown, New Zealand/img (3).avif",
      "/project_airBNB/New/Queenstown, New Zealand/img (4).avif",
      "/project_airBNB/New/Queenstown, New Zealand/img (5).avif",
    ],
    locationType: "new",
    price: "₹722,989 for 5 nights",
  },
  {
    id: 60,
    title: "Virginia, United States",
    image: [
      "/project_airBNB/New/Virginia, United States/img (1).avif",
      "/project_airBNB/New/Virginia, United States/img (2).avif",
      "/project_airBNB/New/Virginia, United States/img (3).avif",
      "/project_airBNB/New/Virginia, United States/img (4).avif",
      "/project_airBNB/New/Virginia, United States/img (5).avif",
    ],
    locationType: "new",
    price: "₹256,592 for 5 nights",
  },

  //OMG!

  {
    id: 61,
    title: "Ponta Delgada, Portugal",
    image: [
      "/project_airBNB/OMG!/Ponta Delgada, Portugal/img (1).avif",
      "/project_airBNB/OMG!/Ponta Delgada, Portugal/img (2).avif",
      "/project_airBNB/OMG!/Ponta Delgada, Portugal/img (3).avif",
      "/project_airBNB/OMG!/Ponta Delgada, Portugal/img (4).avif",
      "/project_airBNB/OMG!/Ponta Delgada, Portugal/img (5).avif",
    ],
    locationType: "OMG!",
    price: "₹860,250 for 5 nights",
  },
  {
    id: 62,
    title: "Farm stay in South Africa",
    image: [
      "/project_airBNB/OMG!/Farm stay in South Africa/img (1).avif",
      "/project_airBNB/OMG!/Farm stay in South Africa/img (2).avif",
      "/project_airBNB/OMG!/Farm stay in South Africa/img (3).avif",
      "/project_airBNB/OMG!/Farm stay in South Africa/img (4).avif",
      "/project_airBNB/OMG!/Farm stay in South Africa/img (5).avif",
    ],
    locationType: "OMG!",
    price: "₹384,031 for 5 nights",
  },
  {
    id: 63,
    title: "Sindun-myeon, Icheon-si, South Korea",
    image: [
      "/project_airBNB/OMG!/Sindun-myeon, Icheon-si, South Korea/img (1).avif",
      "/project_airBNB/OMG!/Sindun-myeon, Icheon-si, South Korea/img (2).avif",
      "/project_airBNB/OMG!/Sindun-myeon, Icheon-si, South Korea/img (3).avif",
      "/project_airBNB/OMG!/Sindun-myeon, Icheon-si, South Korea/img (4).avif",
      "/project_airBNB/OMG!/Sindun-myeon, Icheon-si, South Korea/img (5).avif",
    ],
    locationType: "OMG!",
    price: "₹333,690 for 5 nights",
  },
  {
    id: 64,
    title: "Houseboat in Hua Hin District, Thailand",
    image: [
      "/project_airBNB/OMG!/Houseboat in Hua Hin District, Thailand/img (1).avif",
      "/project_airBNB/OMG!/Houseboat in Hua Hin District, Thailand/img (2).avif",
      "/project_airBNB/OMG!/Houseboat in Hua Hin District, Thailand/img (3).avif",
      "/project_airBNB/OMG!/Houseboat in Hua Hin District, Thailand/img (4).avif",
      "/project_airBNB/OMG!/Houseboat in Hua Hin District, Thailand/img (5).avif",
    ],
    locationType: "OMG!",
    price: "₹527,473 for 5 nights",
  },
  {
    id: 65,
    title: "Tampaksiring, Indonesia",
    image: [
      "/project_airBNB/OMG!/Tampaksiring, Indonesia/img (1).avif",
      "/project_airBNB/OMG!/Tampaksiring, Indonesia/img (5).webp",
      "/project_airBNB/OMG!/Tampaksiring, Indonesia/img (3).avif",
      "/project_airBNB/OMG!/Tampaksiring, Indonesia/img (4).avif",
      "/project_airBNB/OMG!/Tampaksiring, Indonesia/img (2).avif",
    ],
    locationType: "OMG!",
    price: "₹1,432,454 for 5 nights",
  },
  {
    id: 66,
    title: "Treehouse in Sidemen, Indonesia",
    image: [
      "/project_airBNB/OMG!/Treehouse in Sidemen, Indonesia/img (1).avif",
      "/project_airBNB/OMG!/Treehouse in Sidemen, Indonesia/img (2).avif",
      "/project_airBNB/OMG!/Treehouse in Sidemen, Indonesia/img (3).avif",
      "/project_airBNB/OMG!/Treehouse in Sidemen, Indonesia/img (4).avif",
      "/project_airBNB/OMG!/Treehouse in Sidemen, Indonesia/img (5).webp",
    ],
    locationType: "OMG!",
    price: "₹1,887,489 for 5 nights",
  },
  {
    id: 67,
    title: "Plane in Uurainen, Finland",
    image: [
      "/project_airBNB/OMG!/Plane in Uurainen, Finland/img (1).avif",
      "/project_airBNB/OMG!/Plane in Uurainen, Finland/img (2).avif",
      "/project_airBNB/OMG!/Plane in Uurainen, Finland/img (3).avif",
      "/project_airBNB/OMG!/Plane in Uurainen, Finland/img (4).avif",
      "/project_airBNB/OMG!/Plane in Uurainen, Finland/img (5).jpg",
    ],
    locationType: "OMG!",
    price: "₹248,182 for 5 nights",
  },
  {
    id: 68,
    title: "Chiang Mai, Thailand",
    image: [
      "/project_airBNB/OMG!/Chiang Mai, Thailand/img (1).avif",
      "/project_airBNB/OMG!/Chiang Mai, Thailand/img (2).avif",
      "/project_airBNB/OMG!/Chiang Mai, Thailand/img (3).avif",
      "/project_airBNB/OMG!/Chiang Mai, Thailand/img (4).avif",
      "/project_airBNB/OMG!/Chiang Mai, Thailand/img (5).avif",
    ],
    locationType: "OMG!",
    price: "₹198,214 for 5 nights",
  },
  {
    id: 69,
    title: "Dome in Siquijor, Philippines",
    image: [
      "/project_airBNB/OMG!/Dome in Siquijor, Philippines/img (1).avif",
      "/project_airBNB/OMG!/Dome in Siquijor, Philippines/img (2).avif",
      "/project_airBNB/OMG!/Dome in Siquijor, Philippines/img (3).avif",
      "/project_airBNB/OMG!/Dome in Siquijor, Philippines/img (4).avif",
      "/project_airBNB/OMG!/Dome in Siquijor, Philippines/img (5).avif",
    ],
    locationType: "OMG!",
    price: "₹343,079 for 5 nights",
  },
  {
    id: 70,
    title: "Island in El Nido, Philippines",
    image: [
      "/project_airBNB/OMG!/Island in El Nido, Philippines/img (1).avif",
      "/project_airBNB/OMG!/Island in El Nido, Philippines/img (2).avif",
      "/project_airBNB/OMG!/Island in El Nido, Philippines/img (3).avif",
      "/project_airBNB/OMG!/Island in El Nido, Philippines/img (4).avif",
      "/project_airBNB/OMG!/Island in El Nido, Philippines/img (5).webp",
    ],
    locationType: "OMG!",
    price: "₹850,567 for 5 nights",
  },

  //rooms

  {
    id: 71,
    title: "London, United Kingdom",
    image: [
      "/project_airBNB/Rooms/London, United Kingdom/img1.avif",
      "/project_airBNB/Rooms/London, United Kingdom/img2.avif",
      "/project_airBNB/Rooms/London, United Kingdom/img3.jpg",
      "/project_airBNB/Rooms/London, United Kingdom/img4.jpg",
      "/project_airBNB/Rooms/London, United Kingdom/img5.jpg",
    ],
    locationType: "rooms",
    price: "₹321,980 for 5 nights",
  },
  {
    id: 72,
    title: "Room in Bangkok, Thailand",
    image: [
      "/project_airBNB/Rooms/Room in Bangkok, Thailand/img1.avif",
      "/project_airBNB/Rooms/Room in Bangkok, Thailand/img2.avif",
      "/project_airBNB/Rooms/Room in Bangkok, Thailand/img3.avif",
      "/project_airBNB/Rooms/Room in Bangkok, Thailand/img4.avif",
      "/project_airBNB/Rooms/Room in Bangkok, Thailand/img5.avif",
    ],
    locationType: "rooms",
    price: "₹352,930 for 5 nights",
  },
  {
    id: 73,
    title: "Saint Kilda East, Australia",
    image: [
      "/project_airBNB/Rooms/Saint Kilda East, Australia/img1.avif",
      "/project_airBNB/Rooms/Saint Kilda East, Australia/img2.avif",
      "/project_airBNB/Rooms/Saint Kilda East, Australia/img3.avif",
      "/project_airBNB/Rooms/Saint Kilda East, Australia/img4.jpeg",
      "/project_airBNB/Rooms/Saint Kilda East, Australia/img5.avif",
    ],
    locationType: "rooms",
    price: "₹313,130 for 5 nights",
  },
  {
    id: 74,
    title: "Las Palmas de Gran Canaria, Spain",
    image: [
      "/project_airBNB/Rooms/Las Palmas de Gran Canaria, Spain/img1.avif",
      "/project_airBNB/Rooms/Las Palmas de Gran Canaria, Spain/img2.avif",
      "/project_airBNB/Rooms/Las Palmas de Gran Canaria, Spain/img3.avif",
      "/project_airBNB/Rooms/Las Palmas de Gran Canaria, Spain/img4.avif",
      "/project_airBNB/Rooms/Las Palmas de Gran Canaria, Spain/img5.avif",
    ],
    locationType: "rooms",
    price: "₹334,927 for 5 nights",
  },
  {
    id: 75,
    title: "Paris, France",
    image: [
      "/project_airBNB/Rooms/Paris, France/img1.avif",
      "/project_airBNB/Rooms/Paris, France/img2.avif",
      "/project_airBNB/Rooms/Paris, France/img3.avif",
      "/project_airBNB/Rooms/Paris, France/img4.avif",
      "/project_airBNB/Rooms/Paris, France/img5.avif",
    ],
    locationType: "rooms",
    price: "₹276,051 for 5 nights",
  },
  {
    id: 76,
    title: "Cuchillo, Spain",
    image: [
      "/project_airBNB/Rooms/Cuchillo, Spain/img1.avif",
      "/project_airBNB/Rooms/Cuchillo, Spain/img2.avif",
      "/project_airBNB/Rooms/Cuchillo, Spain/img3.avif",
      "/project_airBNB/Rooms/Cuchillo, Spain/img4.avif",
      "/project_airBNB/Rooms/Cuchillo, Spain/img5.avif",
    ],
    locationType: "rooms",
    price: "₹329,937 for 5 nights",
  },
  {
    id: 77,
    title: "Sartrouville, France",
    image: [
      "/project_airBNB/Rooms/Sartrouville, France/img1.avif",
      "/project_airBNB/Rooms/Sartrouville, France/img2.avif",
      "/project_airBNB/Rooms/Sartrouville, France/img3.avif",
      "/project_airBNB/Rooms/Sartrouville, France/img4.avif",
      "/project_airBNB/Rooms/Sartrouville, France/img5.avif",
    ],
    locationType: "rooms",
    price: "₹321,184 for 5 nights",
  },
  {
    id: 78,
    title: "Lyon, France",
    image: [
      "/project_airBNB/Rooms/Lyon, France/img1.avif",
      "/project_airBNB/Rooms/Lyon, France/img2.avif",
      "/project_airBNB/Rooms/Lyon, France/img3.avif",
      "/project_airBNB/Rooms/Lyon, France/img4.avif",
      "/project_airBNB/Rooms/Lyon, France/img5.avif",
    ],
    locationType: "rooms",
    price: "₹288,956 for 5 nights",
  },
  {
    id: 79,
    title: "Room in Bangkok, Thailand",
    image: [
      "/project_airBNB/Rooms/Room in Bangkok, Thailand/img1.avif",
      "/project_airBNB/Rooms/Room in Bangkok, Thailand/img2.avif",
      "/project_airBNB/Rooms/Room in Bangkok, Thailand/img3.avif",
      "/project_airBNB/Rooms/Room in Bangkok, Thailand/img4.avif",
      "/project_airBNB/Rooms/Room in Bangkok, Thailand/img5.avif",
    ],
    locationType: "rooms",
    price: "₹174,342 for 5 nights",
  },
  {
    id: 80,
    title: "中野区弥生町, Japan",
    image: [
      "/project_airBNB/Rooms/中野区弥生町, Japan/img1.avif",
      "/project_airBNB/Rooms/中野区弥生町, Japan/img2.avif",
      "/project_airBNB/Rooms/中野区弥生町, Japan/img3.avif",
      "/project_airBNB/Rooms/中野区弥生町, Japan/img4.avif",
      "/project_airBNB/Rooms/中野区弥生町, Japan/img5.avif",
    ],
    locationType: "rooms",
    price: "₹343,024 for 5 nights",
  },

  //top cities
  {
    id: 81,
    title: "Cape Town, South Africa",
    image: [
      "/project_airBNB/Top cities/Cape Town, South Africa/img (1).avif",
      "/project_airBNB/Top cities/Cape Town, South Africa/img (2).avif",
      "/project_airBNB/Top cities/Cape Town, South Africa/img (3).avif",
      "/project_airBNB/Top cities/Cape Town, South Africa/img (4).avif",
      "/project_airBNB/Top cities/Cape Town, South Africa/img (5).avif",
    ],
    locationType: "top cities",
    price: "₹307,038 for 7 nights",
  },
  {
    id: 82,
    title: "Chippendale, Australia",
    image: [
      "/project_airBNB/Top cities/Chippendale, Australia/img (1).avif",
      "/project_airBNB/Top cities/Chippendale, Australia/img (5).jpg",
      "/project_airBNB/Top cities/Chippendale, Australia/img (3).avif",
      "/project_airBNB/Top cities/Chippendale, Australia/img (4).avif",
      "/project_airBNB/Top cities/Chippendale, Australia/img (2).avif",
    ],
    locationType: "top cities",
    price: "₹326,692 for 5 nights",
  },
  {
    id: 83,
    title: "Dubai, United Arab Emirates",
    image: [
      "/project_airBNB/Top cities/Dubai, United Arab Emirates/img (1).avif",
      "/project_airBNB/Top cities/Dubai, United Arab Emirates/img (2).avif",
      "/project_airBNB/Top cities/Dubai, United Arab Emirates/img (3).avif",
      "/project_airBNB/Top cities/Dubai, United Arab Emirates/img (4).avif",
      "/project_airBNB/Top cities/Dubai, United Arab Emirates/img (5).avif",
    ],
    locationType: "top cities",
    price: "₹342,387 for 5 nights",
  },
  {
    id: 84,
    title: "Marrakesh, Morocco",
    image: [
      "/project_airBNB/Top cities/Marrakesh, Morocco/img (1).avif",
      "/project_airBNB/Top cities/Marrakesh, Morocco/img (2).avif",
      "/project_airBNB/Top cities/Marrakesh, Morocco/img (3).avif",
      "/project_airBNB/Top cities/Marrakesh, Morocco/img (4).avif",
      "/project_airBNB/Top cities/Marrakesh, Morocco/img (5).jpg",
    ],
    locationType: "top cities",
    price: "₹280,340 for 5 nights",
  },
  {
    id: 85,
    title: "Nazlet El-Semman, Egypt",
    image: [
      "/project_airBNB/Top cities/Nazlet El-Semman, Egypt/img (1).avif",
      "/project_airBNB/Top cities/Nazlet El-Semman, Egypt/img (2).avif",
      "/project_airBNB/Top cities/Nazlet El-Semman, Egypt/img (3).avif",
      "/project_airBNB/Top cities/Nazlet El-Semman, Egypt/img (4).avif",
      "/project_airBNB/Top cities/Nazlet El-Semman, Egypt/img (5).avif",
    ],
    locationType: "top cities",
    price: "₹341,557 for 5 nights",
  },
  {
    id: 86,
    title: "Treehouse in Gaular, Norway",
    image: [
      "/project_airBNB/Top cities/Treehouse in Gaular, Norway/img (1).avif",
      "/project_airBNB/Top cities/Treehouse in Gaular, Norway/img (5).webp",
      "/project_airBNB/Top cities/Treehouse in Gaular, Norway/img (3).avif",
      "/project_airBNB/Top cities/Treehouse in Gaular, Norway/img (4).avif",
      "/project_airBNB/Top cities/Treehouse in Gaular, Norway/img (2).avif",
    ],
    locationType: "top cities",
    price: "₹341,735 for 5 nights",
  },
  {
    id: 87,
    title: "Rome, Italy",
    image: [
      "/project_airBNB/Top cities/Rome, Italy/img (1).avif",
      "/project_airBNB/Top cities/Rome, Italy/img (2).avif",
      "/project_airBNB/Top cities/Rome, Italy/img (3).avif",
      "/project_airBNB/Top cities/Rome, Italy/img (4).avif",
      "/project_airBNB/Top cities/Rome, Italy/img (5).avif",
    ],
    locationType: "top cities",
    price: "₹307,035 for 5 nights",
  },
  {
    id: 88,
    title: "South Brisbane, Australia",
    image: [
      "/project_airBNB/Top cities/South Brisbane, Australia/img (1).avif",
      "/project_airBNB/Top cities/South Brisbane, Australia/img (2).jpg",
      "/project_airBNB/Top cities/South Brisbane, Australia/img (3).avif",
      "/project_airBNB/Top cities/South Brisbane, Australia/img (4).jpg",
      "/project_airBNB/Top cities/South Brisbane, Australia/img (5).jpg",
    ],
    locationType: "top cities",
    price: "₹331,537 for 5 nights",
  },
  {
    id: 89,
    title: "South Yarra, Australia",
    image: [
      "/project_airBNB/Top cities/South Yarra, Australia/img (1).avif",
      "/project_airBNB/Top cities/South Yarra, Australia/img (2).avif",
      "/project_airBNB/Top cities/South Yarra, Australia/img (3).avif",
      "/project_airBNB/Top cities/South Yarra, Australia/img (4).avif",
      "/project_airBNB/Top cities/South Yarra, Australia/img (5).avif",
    ],
    locationType: "top cities",
    price: "₹320,486 for 5 nights",
  },
  {
    id: 90,
    title: "Pererenan, Indonesia",
    image: [
      "/project_airBNB/Top cities/Pererenan, Indonesia/img (1).avif",
      "/project_airBNB/Top cities/Pererenan, Indonesia/img (2).avif",
      "/project_airBNB/Top cities/Pererenan, Indonesia/img (3).avif",
      "/project_airBNB/Top cities/Pererenan, Indonesia/img (4).avif",
      "/project_airBNB/Top cities/Pererenan, Indonesia/img (5).avif",
    ],
    locationType: "top cities",
    price: "₹330,065 for 5 nights",
  },

  // top of the world

  {
    id: 91,
    title: "Blue River, Colorado, United States",
    image: [
      "/project_airBNB/Top of the world/Blue River, Colorado, United States/img1.avif",
      "/project_airBNB/Top of the world/Blue River, Colorado, United States/img2.avif",
      "/project_airBNB/Top of the world/Blue River, Colorado, United States/img3.avif",
      "/project_airBNB/Top of the world/Blue River, Colorado, United States/img4.avif",
      "/project_airBNB/Top of the world/Blue River, Colorado, United States/img5.avif",
    ],
    locationType: "top of the world",
    price: "₹312,645 for 5 nights",
  },
  {
    id: 92,
    title: "Keylong, India",
    image: [
      "/project_airBNB/Top of the world/Keylong, India/img1.avif",
      "/project_airBNB/Top of the world/Keylong, India/img2.avif",
      "/project_airBNB/Top of the world/Keylong, India/img3.jpg",
      "/project_airBNB/Top of the world/Keylong, India/img4.jpg",
      "/project_airBNB/Top of the world/Keylong, India/img5.avif",
    ],
    locationType: "top of the world",
    price: "₹349,035 for 5 nights",
  },
  {
    id: 93,
    title: "Rakchham, India",
    image: [
      "/project_airBNB/Top of the world/Rakchham, India/img1.jpeg",
      "/project_airBNB/Top of the world/Rakchham, India/img2.jpeg",
      "/project_airBNB/Top of the world/Rakchham, India/img3.webp",
      "/project_airBNB/Top of the world/Rakchham, India/img4.avif",
      "/project_airBNB/Top of the world/Rakchham, India/img5.avif",
    ],
    locationType: "top of the world",
    price: "₹394,945 for 5 nights",
  },
  {
    id: 94,
    title: "Pintag, Ecuador",
    image: [
      "/project_airBNB/Top of the world/Pintag, Ecuador/img (1).avif",
      "/project_airBNB/Top of the world/Pintag, Ecuador/img (2).avif",
      "/project_airBNB/Top of the world/Pintag, Ecuador/img (3).avif",
      "/project_airBNB/Top of the world/Pintag, Ecuador/img (4).avif",
      "/project_airBNB/Top of the world/Pintag, Ecuador/img (5).avif",
    ],
    locationType: "top of the world",
    price: "₹471,292 for 5 nights",
  },
  {
    id: 95,
    title: "Cripple Creek, Colorado, United States",
    image: [
      "/project_airBNB/Top of the world/Cripple Creek, Colorado, United States/img (1).avif",
      "/project_airBNB/Top of the world/Cripple Creek, Colorado, United States/img (2).avif",
      "/project_airBNB/Top of the world/Cripple Creek, Colorado, United States/img (3).avif",
      "/project_airBNB/Top of the world/Cripple Creek, Colorado, United States/img (4).avif",
      "/project_airBNB/Top of the world/Cripple Creek, Colorado, United States/img (5).avif",
    ],
    locationType: "top of the world",
    price: "₹348,463 for 5 nights",
  },
  {
    id: 96,
    title: "Breckenridge, Colorado, United States",
    image: [
      "/project_airBNB/Top of the world/Breckenridge, Colorado, United States/img (1).avif",
      "/project_airBNB/Top of the world/Breckenridge, Colorado, United States/img (2).avif",
      "/project_airBNB/Top of the world/Breckenridge, Colorado, United States/img (3).avif",
      "/project_airBNB/Top of the world/Breckenridge, Colorado, United States/img (4).avif",
      "/project_airBNB/Top of the world/Breckenridge, Colorado, United States/img (5).avif",
    ],
    locationType: "top of the world",
    price: "₹405,681 for 5 nights",
  },
  {
    id: 97,
    title: "Fairplay, Colorado, United States",
    image: [
      "/project_airBNB/Top of the world/Fairplay, Colorado, United States/img (1).avif",
      "/project_airBNB/Top of the world/Fairplay, Colorado, United States/img (2).avif",
      "/project_airBNB/Top of the world/Fairplay, Colorado, United States/img (3).avif",
      "/project_airBNB/Top of the world/Fairplay, Colorado, United States/img (4).avif",
      "/project_airBNB/Top of the world/Fairplay, Colorado, United States/img (5).webp",
    ],
    locationType: "top of the world",
    price: "₹209,774 for 5 nights",
  },
  {
    id: 98,
    title: "dome in Cusco, Peru",
    image: [
      "/project_airBNB/Top of the world/dome in Cusco, Peru/img (1).avif",
      "/project_airBNB/Top of the world/dome in Cusco, Peru/img (2).avif",
      "/project_airBNB/Top of the world/dome in Cusco, Peru/img (3).avif",
      "/project_airBNB/Top of the world/dome in Cusco, Peru/img (4).avif",
      "/project_airBNB/Top of the world/dome in Cusco, Peru/img (5).avif",
    ],
    locationType: "top of the world",
    price: "₹344,536 for 5 nights",
  },
  {
    id: 99,
    title: "Idaho Springs, Colorado, United States",
    image: [
      "/project_airBNB/Top of the world/Idaho Springs, Colorado, United States/img (1).avif",
      "/project_airBNB/Top of the world/Idaho Springs, Colorado, United States/img (2).avif",
      "/project_airBNB/Top of the world/Idaho Springs, Colorado, United States/img (3).avif",
      "/project_airBNB/Top of the world/Idaho Springs, Colorado, United States/img (4).avif",
      "/project_airBNB/Top of the world/Idaho Springs, Colorado, United States/img (5).avif",
    ],
    locationType: "top of the world",
    price: "₹174,590 for 5 nights",
  },
  {
    id: 100,
    title: "Sacred Valley, Peru",
    image: [
      "/project_airBNB/Top of the world/Sacred Valley, Peru/img (1).avif",
      "/project_airBNB/Top of the world/Sacred Valley, Peru/img (2).avif",
      "/project_airBNB/Top of the world/Sacred Valley, Peru/img (3).avif",
      "/project_airBNB/Top of the world/Sacred Valley, Peru/img (4).avif",
      "/project_airBNB/Top of the world/Sacred Valley, Peru/img (5).avif",
    ],
    locationType: "top of the world",
    price: "₹252,711 for 5 nights",
  },
];
